workflows:
  android-debug:
    name: Android Debug Workflow
    environment:
      flutter: stable
    scripts:
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      
